'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { api, Document, Persona, Comment } from '@/lib/api';
import { DocumentViewer } from '@/components/DocumentViewer';
import { PersonaPanel } from '@/components/PersonaPanel';

export default function DocumentPage() {
  const params = useParams();
  const docId = params.id as string;
  
  const [document, setDocument] = useState<Document | null>(null);
  const [content, setContent] = useState('');
  const [personas, setPersonas] = useState<Persona[]>([]);
  const [selectedPersonas, setSelectedPersonas] = useState<string[]>([]);
  const [comments, setComments] = useState<Comment[]>([]);
  const [loading, setLoading] = useState(true);
  const [isReviewing, setIsReviewing] = useState(false);

  useEffect(() => {
    if (docId) {
      loadDocument();
      loadPersonas();
    }
  }, [docId]);

  const loadDocument = async () => {
    try {
      const [doc, contentRes] = await Promise.all([
        api.getDocument(docId),
        api.getDocumentContent(docId),
      ]);
      setDocument(doc);
      setContent(contentRes.content);
    } catch (error) {
      console.error('Failed to load document:', error);
    } finally {
      setLoading(false);
    }
  };

  const loadPersonas = async () => {
    try {
      const personas = await api.listPersonas();
      setPersonas(personas);
      // Pre-select all personas
      setSelectedPersonas(personas.map(p => p.id));
    } catch (error) {
      console.error('Failed to load personas:', error);
    }
  };

  const handleVersionSelect = async (version: string) => {
    try {
      const contentRes = await api.getDocumentContent(docId, version);
      setContent(contentRes.content);
    } catch (error) {
      console.error('Failed to load version:', error);
    }
  };

  const handleReviewRequest = async (personaIds: string[]) => {
    setIsReviewing(true);
    // TODO: Implement actual AI review
    // For now, simulate with timeout
    setTimeout(() => {
      const selectedPersonaList = personas.filter(p => personaIds.includes(p.id));
      const mockComments: Comment[] = selectedPersonaList.map((persona, idx) => ({
        id: `mock-${idx}`,
        content: `This is a sample review comment from ${persona.name}. In a real implementation, this would be generated by the AI based on the persona's system prompt and focus areas.`,
        persona_id: persona.id,
        persona_name: persona.name,
        persona_color: persona.color,
        document_id: docId,
        version_hash: document?.versions[0]?.commit_hash || '',
        anchor: {
          file_path: 'document.md',
          start_line: 1 + idx * 3,
          end_line: 1 + idx * 3,
        },
        created_at: new Date().toISOString(),
      }));
      setComments(mockComments);
      setIsReviewing(false);
    }, 2000);
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center">
        <div className="text-slate-500">Loading...</div>
      </div>
    );
  }

  if (!document) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center">
        <div className="text-center">
          <p className="text-slate-500 mb-4">Document not found</p>
          <Link href="/documents" className="text-indigo-600 hover:underline">
            Back to documents
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="h-screen flex flex-col">
      {/* Top nav */}
      <header className="bg-white border-b px-4 py-2 flex items-center gap-4">
        <Link href="/documents" className="text-slate-500 hover:text-slate-700">
          ← Back
        </Link>
        <span className="text-slate-300">|</span>
        <span className="font-semibold text-slate-800">{document.title}</span>
      </header>

      {/* Main content */}
      <div className="flex-1 flex overflow-hidden">
        <div className="flex-1 overflow-hidden">
          <DocumentViewer
            document={document}
            content={content}
            comments={comments}
            onVersionSelect={handleVersionSelect}
          />
        </div>
        <PersonaPanel
          personas={personas}
          selectedIds={selectedPersonas}
          onSelectionChange={setSelectedPersonas}
          onReviewRequest={handleReviewRequest}
          isReviewing={isReviewing}
        />
      </div>
    </div>
  );
}
